apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-z5cc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-z5cc
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-z5cc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-z5cc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-z5cc
    spec:
      containers:
      - image: quay.io/mbasti-test-org/happy-path-xygk-tenant/appstudio/dc-metro-map-z5cc@sha256:977dbb670b9ec3c77ca9cd337b02cf6fe847be6016d515803ca3eb4cc80d7b9a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
